name: Run Checks

on: [push, workflow_dispatch]
env:
  NODE_VERSION: 18

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --ignore-scripts --immutable

      - name: Run Checks
        run: yarn checks
